language: cpp

git:
    depth: false

compiler:
    - clang++
    - g++

services:
    - docker

before_install:
    - docker pull epitechcontent/epitest-docker

notifications:
  email:
    recipients:
        - joseph.vidal@epitech.eu
        - alexandre.seignol@epitech.eu
        - marc-antoine.thenard@epitech.eu
    on_success: never
    on_failure: always

jobs:
    include:
        - stage: build
          name: "Build"
          script:
            - docker run -v $PWD:/project epitechcontent/epitest-docker bash -c "cd project && make"